spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true

  datasource:
    url: jdbc:h2:mem:project
    username: sa
    password:
    driver-class-name: org.h2.Driver

# jwt secret key 설정
jwt:
  secret: validSecretKey
  refresh-secret: refreshSecretKey
